- alias: Living Room Lights Adjust Brightness
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.livingroom_brightness
    action:
      - service: light.turn_on
        data_template:
          entity_id: group.group.light
          brightness: '{{ trigger.to_state.state | int }}'